name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Pulling changes"
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - run: git pull

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "yarn"
                  registry-url: "https://registry.npmjs.org"

            - name: Installing
              run: yarn install

            - name: Commiting changes
              run: |
                  cp -rf dist/* docs
                  if [ -z "$(git status --porcelain)" ]; then
                    echo "no changes, skip ci"
                  else
                    git config user.name "GitHub Actions Bot"
                    git config user.email "<>"
                    git add docs
                    git commit -m "chore (docs): docs updated [ci skip]"
                    git push https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                    git pull --ff-only 
                    git push --follow-tags
                  fi
